RAW_HEADERS = [
    "post_id",
    "post_url",
    "platform",
    "genre",
    "account_name",
    "account_id",
    "account_handle",
    "account_url",
    "follower_count",
    "posted_at",
    "posted_date",
    "weekday",
    "hour",
    "time_slot",
    "post_type",
    "text",
    "hook_text",
    "text_length",
    "emoji_count",
    "hashtag_count",
    "mention_count",
    "hashtags",
    "mentions",
    "link_urls",
    "has_external_link",
    "image_count",
    "has_image",
    "has_video",
    "has_media",
    "image_urls",
    "video_urls",
    "quote_count",
    "reply_count",
    "repost_count",
    "like_count",
    "bookmark_count",
    "impression_count",
    "matched_keywords",
    "matched_accounts",
    "matched_sources",
    "source_types",
    "is_from_account_monitor",
    "is_from_keyword_search",
    "first_collected_at",
    "last_metrics_update_at",
    "last_source_sync_at",
    "raw_payload_json",
]

DASHBOARD_HEADERS = ["分類", "指標", "値", "示唆", "更新日時"]

COLLECTION_HEADERS = [
    "投稿ID",
    "投稿URL",
    "アカウント名",
    "アカウントID",
    "アカウントURL",
    "フォロワー数",
    "投稿日時",
    "曜日",
    "時間帯",
    "投稿種別",
    "投稿本文",
    "投稿本文冒頭",
    "文字数",
    "ハッシュタグ数",
    "メンション数",
    "絵文字数",
    "外部リンクあり",
    "画像あり",
    "画像枚数",
    "動画あり",
    "メディアあり",
    "画像URL一覧",
    "動画URL一覧",
    "いいね数",
    "リポスト数",
    "返信数",
    "引用数",
    "保存数",
    "インプレッション数",
    "監視アカウント一致",
    "監視キーワード一致",
    "一致元",
    "バズ判定",
    "アカウント内上位20%",
    "キーワード群内上位20%",
    "切り口",
    "書き出し型",
    "伸びた理由",
    "再現ポイント",
]

REVIEW_HEADERS = [
    "投稿ID",
    "元投稿URL",
    "アカウント名",
    "投稿本文",
    "投稿本文冒頭",
    "メディア種別",
    "画像URL一覧",
    "動画URL一覧",
    "保存メディアURL",
    "保存メディアパス",
    "ドライブ画像ファイルID",
    "ドライブ動画ファイルID",
    "Threads公開画像URL",
    "Threads公開動画URL",
    "いいね数",
    "インプレッション数",
    "伸びた理由",
    "リライト方針A",
    "リライト案A",
    "リライト方針B",
    "リライト案B",
    "採用案",
    "転載可否",
    "投稿可否",
    "X投稿するか",
    "Threads投稿するか",
    "確認メモ",
    "投稿先タブ",
    "最終同期日時",
]

QUEUE_HEADERS = [
    "キューID",
    "元投稿ID",
    "元投稿URL",
    "アカウント名",
    "投稿文",
    "画像URL",
    "動画URL",
    "ドライブ画像ファイルID",
    "ドライブ動画ファイルID",
    "Threads画像URL",
    "Threads動画URL",
    "採用案",
    "転載可否",
    "確認メモ",
    "X投稿対象",
    "X投稿状態",
    "X投稿日時",
    "Threads投稿対象",
    "Threads投稿状態",
    "Threads投稿日時",
    "キュー追加日時",
    "最終更新日時",
]

SYSTEM_HEADERS = ["key", "value", "updated_at"]

REVIEW_DEFAULTS = {
    "リライト方針A": "軽整形",
    "リライト方針B": "再構成",
    "採用案": "未選択",
    "転載可否": "未確認",
    "投稿可否": "未承認",
    "X投稿するか": "投稿しない",
    "Threads投稿するか": "投稿しない",
    "投稿先タブ": "ライバー_03_投稿キュー",
}

REVIEW_DROPDOWNS = {
    "採用案": ["未選択", "A", "B"],
    "転載可否": ["未確認", "転載OK", "要加工", "NG"],
    "投稿可否": ["未承認", "投稿OK"],
    "X投稿するか": ["投稿する", "投稿しない"],
    "Threads投稿するか": ["投稿する", "投稿しない"],
}

QUEUE_DROPDOWNS = {
    "X投稿対象": ["投稿する", "投稿しない"],
    "X投稿状態": ["投稿待ち", "投稿済み", "スキップ", "エラー"],
    "Threads投稿対象": ["投稿する", "投稿しない"],
    "Threads投稿状態": ["投稿待ち", "投稿済み", "スキップ", "エラー"],
}
